### ISSUE TITLE
Road directions should have independent U-turn settings

### ISSUE THREAD

**Issue by HarryBotter2333** [slyh/Cities2-Various-Mods#12]
Nice job @slyh, I'm already happy with the road direction modes, they work great :+1: 

When we do not need to fully protect the left turn on this road section, we can skip the left turn protection.This way you can safely turn the vehicle around.

But now we cannot delete the left turn road. 
This means that we will still see vehicles that turn left and get stuck by straight vehicles. 

Of course, there is no problem running in the "Protected Left-Turns" mode.

![Road U-turn settings](https://github.com/slyh/Cities2-Various-Mods/assets/43106121/ed8620c5-75bf-4b21-9aff-9a31d5336906)

![car 2023-11-23](https://github.com/slyh/Cities2-Various-Mods/assets/43106121/f79bc9c0-35b1-4282-8a10-6b996df97650)

**Comment by slyh** [comment]
I overlooked that, will separate those two options in the next update.

**Comment by slyh** [comment]
Fixed in release [2023.11.23-hotfix](https://github.com/slyh/Cities2-Various-Mods/releases/tag/2023.11.23-hotfix)

**Comment by HarryBotter2333** [comment]
Very helpful, that's what I wanted :) , thank you @slyh
