### ISSUE TITLE
Do you have to do these one intersection at a time?

### ISSUE THREAD

**Issue by tethlah** [slyh/Cities2-Various-Mods#13]
When I select an entire line of intersections and select my settings, then hit save, only the first intersection I selected seems to have applied the settings.  So do you have to select intersections one by one, reselect all the settings you want, and hit save, one at a time?

**Comment by HarryBotter2333** [comment]
Yes, only the first node is saved, maybe it can be saved directly to other intersections later by copy and paste.

Another point is that the current version does not recommend changing the road structure multiple times. It will reset the road direction settings.

**Comment by slyh** [comment]
Feel free to reopen the issue if anything remains unclear.

**Comment by tethlah** [comment]
Makes sense.  Maybe the ability to save a default setting or something could be useful.  I know in every city I've done so far, probably 80-90% of my intersections end up using the same settings.  It could save a lot of clicking if you could save a default or favorite or something and then apply it.  So far, I've gotten about a quarter of my intersections done and that's taken an hour lol.

**Comment by slyh** [comment]
I will provide a default configuration for new setups instead of leaving them completely blank.
