### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by SuperYYT** [slyh/Cities2-Various-Mods#15]
We introduced this mod to the Chinese community! There are also members who have made a third-party Chinese version. Is there any opportunity to add multi-language support so that we can contribute to the localization of this mod?
Chinese version: https://www.cslbbs.net/resources/trafficlightsenhancement.52/

**Comment by slyh** [comment]
I will implement multi-language support after refining some of the rough edges within the UI.

**Comment by SuperYYT** [comment]
> I will implement multi-language support after refining some of the rough edges within the UI.

Thank you so much！

**Comment by PsykotropyK** [comment]
> I will implement multi-language support after refining some of the rough edges within the UI.

If you need French translation let me know how I can help

**Comment by slyh** [comment]
I have just added multi-language support. Please refer to [TrafficLightsEnhancement/Localizations](https://github.com/slyh/Cities2-Various-Mods/tree/main/TrafficLightsEnhancement/Localisations) for examples and format. The game currently supports the following locale IDs:

de-DE
en-US
es-ES
fr-FR
it-IT
ja-JP
ko-KR
pl-PL
pt-BR
ru-RU
zh-HANS
zh-HANT

However, a small part of the UI has not yet been adapted for multiple languages. They will have to wait until the UI rewrite is finished.
