### ISSUE TITLE
changing direction of one lane breaks directions in other lanes on whole intersection

### ISSUE THREAD

**Issue by 0rangeGhost** [slyh/Cities2-Various-Mods#18]
so if you want to change only one lane - you will have to set up every other lane. would be nice if mod could read vanilla lane directions and used them as base to further changes of lane directions
![image](https://github.com/slyh/Cities2-Various-Mods/assets/52754229/61a1ee4e-d0e7-48a0-be90-2e96449400b7)
![image](https://github.com/slyh/Cities2-Various-Mods/assets/52754229/3e0f4840-6793-42e9-90d6-6ce8f702d0c3)

**Comment by slyh** [comment]
Mitigated in 0.2.1-RC. It will provide a default direction instead of leaving it completely blank.
