### ISSUE TITLE
Issues with 4 way traffic still crossing eachother

### ISSUE THREAD

**Issue by tommerty** [slyh/Cities2-Various-Mods#19]
![Image](https://github.com/slyh/Cities2-Various-Mods/assets/86270372/e0d89aeb-4263-4beb-ac47-501842b0e60c)

No matter what section, if one direction is going straight, the opposite traffic still attempt to turn on top of them, causing traffic. I've noticed it only with some intersections, can't find the pattern. I've tried lane management with dedicated lanes, etc. Any advice, or is this just a bug?

PS Love the mod, thank you for releasing it ❤

**Comment by timfrombriz** [comment]
Your lane config is a bit broken.  For example, The bottom intersection has 3 lanes, the 2 leftmost have up permitted, the middle has left turn which collides with the left lane going straight.  Your East->West has both lanes going all directions.   Perhaps try setting lane rules first which do not collide with traffic travelling in the same direction and see if that causes the simulation to function better.

**Comment by slyh** [comment]
Could you record a video showing the behaviour of vehicles and the traffic signals?

**Comment by ColdCathode01** [comment]
This Junction is a 4 Way but it has a 1 way road facing away so it is treated as a 3 Way Junction (Only 3 entry points for traffic into the junction). Only the 3 Way signal rules will apply here.

**Comment by slyh** [comment]
> This Junction is a 4 Way but it has a 1 way road facing away so it is treated as a 3 Way Junction (Only 3 entry points for traffic into the junction). Only the 3 Way signal rules will apply here. Its likely you have the Vanilla signals still set for 3 Ways at the junction, try changing that and see what happens??

A very likely cause.

**Comment by tommerty** [comment]
Hey all, yeah I figured out some lane maths was wrong and it just wasn't playing nicely, happy to close this out and blame good 'ol user error on this!
