### ISSUE TITLE
Traffic Lights mod not working at all

### ISSUE THREAD

**Issue by Jovzin** [slyh/Cities2-Various-Mods#4]
Hello team.
First thank you for this mod it looks great. 
But I am unable to make it work.
Steps I did 
1/ Download  BepInEx_UnityMono_x64_6.0.0-pre.1.zip  from https://github.com/BepInEx/BepInEx/releases 
2/ Copy it to Cities Skylines 2 folder. 
3/ Run the game and load my save so BepInEx can create its files and folders.
4/ Download Traffic Lights improvement from https://paradoxmods.net/files/25-traffic-lights-improvement/ 
5/ Copy whole folder to Cities Skylines 2/BepInEx/plugins/C2VM_TrafficLightsEnhancement/TrafficLightsEnhancement.dll
6/ Run the game and load my save game file. 
7/ Click on the Road maintenance tab and click on the Traffic lights button and nothing . No top left corner info window showing.

8/ Tried to copy only the dll file under Cities Skylines 2/BepInEx/plugins/TrafficLightsEnhancement.dll 
9/ Run the game load my save game , and game crashing.

From BepInEx logs looks like it is not loading any plugin at all : 

[Message: Preloader] BepInEx 6.0.0-pre.1 - Cities2
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   : Preloader] Running under Unity v2022.3.7.9732149
[Info   : Preloader] CLR runtime version: 4.0.30319.42000
[Info   : Preloader] Supports SRE: True
[Message: Preloader] Preloader started
[Info   :AssemblyPatcher] Loaded 1 patcher type from [BepInEx.Preloader.Unity 6.0.0.0]
[Info   : Preloader] 1 patcher plugin loaded
[Info   : Preloader] 163 assemblies discovered
[Message:AssemblyPatcher] Executing 1 patch(es)
[Message: Preloader] Preloader finished
[Message:   BepInEx] Chainloader initialized
[Info   :   BepInEx] 0 plugins to load
[Message:   BepInEx] Chainloader startup complete
[Info   :   Console] Logs at C:/Users/Jovzin/AppData/LocalLow/Colossal Order/Cities Skylines II/Logs

Could it be that the mod is now compatible with save game files and I need to start a new city ?
Should I disable the dev mode ? Could this be issue too that I have enabled the Dev mode in the past ?
Do I need to create some new streets in my city to make it work ? It will not work on already placed 3 and 4 lanes roads ?  

Thank you for your help.
Jozef

**Comment by slyh** [comment]
You need the [Bleeding Edge build](https://builds.bepinex.dev/projects/bepinex_be) of BepInEx 6, as the pre-release version available on GitHub is very old (dated August 2022).

The mod is compatible with existing saves and roads. It will save additional data into your save file (the selected pattern). While I can't guarantee it's 100% safe, it's very unlikely to cause issues, even if you uninstall the mod at a later time. However, I would strongly recommend testing it first.

Regarding dev mode, I'm not aware of any compatibility issues.

**Comment by HarryBotter2333** [comment]
**Correct name:[BepInEx-Unity.Mono-win-x64-6.0.0-be.674+82077ec.zip]**

Another point is that I also downloaded this version and it can't run. You need to download this win version and name it accordingly.

**Comment by Jovzin** [comment]
Thank you guys.
Much appreciate that. 
Working now.
