### ISSUE TITLE
Crashes latest patch of the game

### ISSUE THREAD

**Issue by Oliver123G** [slyh/Cities2-Various-Mods#45]

**Comment by sharelj** [comment]
same crashing on 1.0.15f

**Comment by ericbrownaustin** [comment]
Same issue here

**Comment by adalinesimonian** [comment]
Duplicate of #40

**Comment by slyh** [comment]
Should be fixed in v0.2.3-alpha.

**Comment by pikachukaki** [comment]
v0.2.3-alpha working properly....
I wanna ask without opening new issue it is posible to add something similar with TPME that allow to draw in nodes so the cars obey the lines we place?
